# Rarefaction and random seeds {#rarefaction_randomw_seeds_chap}

In this chapter we will carry out iterative rarefaction using random seeds.
This is to help understand what random seeds are and why they are used.
We won't do anything of value with the results in this chapter, instead the code and knowledge we create here will allow us to carry out the alpha and beta diversity in the next chapters.

## Rarefaction jupyter notebook

Create a new R jupyter-notebook called "Rarefaction_and_random_seeds.ipynb".

## Random seeds

What are random seeds?

Random seeds are numbers that computational tasks use to determine how they will carry out a random task.

### Random sampling

To demonstrate this we will use the R function `sample()`. 
The function randomly samples a set of numbers.

Create the below code in a code cell.

```{R, eval=FALSE}
#Create a vector containing the numbers 0 to 10
num_vec <- 0:10
#Randomly sample 5 of these numbers
sample(x = num_vec, size = 5)
```

If you run the code you will get five random single digit numbers.

Run this multiple times and you will hopefully see the sampled numbers are different every time.

### Sampling with replacement

You may also notice that within each sample there are no repeating numbers.
You can change this by adding the options `replace = TRUE`.

Try this out in a new cell.

```{R, eval=FALSE}
#Create a vector containing the numbers 0 to 10
num_vec <- 0:10
#Randomly sample 5 of these numbers with replacement
sample(x = num_vec, size = 5, replace = TRUE)
```

Run this a few times and you will hopefully notice that there are repeats.

When sampling with replacement you put back any results back into the sampling pool.
When sampling without replacement you don't put back any results into the sampling pool.

The famous example is sampling green and yellow balls from a bag.
If you had a bag with 1000 balls and you wanted a rough idea of the ratio of yellow and green balls you could count the number of these balls of only 50.
Without replacement you would take out a ball, mark its colour and throw it in a separate container.
With replacement you would take out a ball, mark its colour and put it back into the intial bag, meanig it could possibly be recounted.

Importantly for us rarefaction uses sampling without replacement.

### Setting a random seed

We'll sample, without replacement, the numbers one more time in a new cell.
However, this time we will set the random seed with the function `seet.seed()`.

```{R, eval=FALSE}
#Set random seed
set.seed(1234)
#Create a vector containing the numbers 0 to 10
num_vec <- 0:10
#Randomly sample 5 of these numbers
sample(x = num_vec, size = 5)
#Reset random seed
set.seed(NULL)
```

Before we explain the code further, try running the cell multiple times.
If it is identical to the above code you will get the numbers "9, 5, 4, 3, & 6".

How come you are getting these results if it is random?

True randomness is pretty much impossible, especially in computing.
To get around this many programs use seeds to determine how random tasks will be carried out.
Various programs that use random seeds include:

- Sampling tools such as `sample()` and rarefaction
- Creating bootstrapped phylogenies
- Creating procedural content such as building Minecraft worlds

Therefore if you run a tool that will use randomness you will always get the same results if:

- You use the same random seed
- You use the same data

In fact, run the below code in a new code cell and you may notice a similarity with your previous output.

```{R, eval=FALSE}
#Set random seed
set.seed(1234)
#Create a vector containing the numbers 0 to 10
num_vec <- 10:19
#Randomly sample 5 of these numbers
sample(x = num_vec, size = 5)
#Reset random seed
set.seed(NULL)
```

That's right, sample will always take the 10th (9/19), 6th (5/15), 5th (4/14), 4th (3/13), and 7th (6/16) values if it is given the random seed of (1234) and provided with a 11 length vector.

Setting our randomness is incredible beneficial for reproducibility in research.

When you carry out analysis you may need to redo some work. 
This could be due to reviewer comments or you want to incorporate some new methods.
As long as you saved the random seeds you used you can get the same results where you need to.
It also means others can replicate your results.

That is why we set a random seed at the start of the cell but why do we then run the line `set.seed()`?

The normal operation of R means that, in effect, its random seed changes every time it is used.
This means R normally randomly determines randomness.
This is how it should be until we want to set the randomness.
It is therefore good practice to set the seed to `NULL` after you have utilised your set seeds.
This will revert the seed to its normal random operations.

