# Resources

## Rarefaction resources

- Journal papers
  - ["To rarefy or not to rarefy: robustness and efficiency trade-offs of rarefying microbiome data"](https://academic.oup.com/bioinformatics/article/38/9/2389/6536959)
  - ["Rarefaction is currently the best approach to control for uneven sequencing effort in amplicon sequence analyses"](https://journals.asm.org/doi/10.1128/msphere.00354-23)
  - ["Waste Not, Want Not: Why Rarefying Microbiome Data Is Inadmissible"](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531)

## MaAsLin3 resources

Below are various resources for MaAsLin3:

- [MaAsLin3 github main page](https://github.com/biobakery/Maaslin3)
- [MaAsLin3 Tutorial](https://github.com/biobakery/biobakery/wiki/MaAsLin3)
    - [Interactions](https://github.com/biobakery/biobakery/wiki/MaAsLin3#43-interactions): Seeing interactions or 2 effects
        - Note: It may be easier to create a metadata column combining 2 categorical metadata columns rather than using interactions
    - [Level contrasts](https://github.com/biobakery/biobakery/wiki/MaAsLin3#44-level-contrasts): Comparison of ordered effects
        - This will compare second level against the first, third level against the second etc.
        - No random effects can be used in the formula when using and ordered effect
    - [Group-wise differences](https://github.com/biobakery/biobakery/wiki/MaAsLin3#45-group-wise-differences): Produce one overall p/q-value for the variable
        - Uses an ANOVA or ANOVA-like procedure
- [Explanation of hierarchical models](https://mfviz.com/hierarchical-models/)
- [Martin Speekenbrink's chapter on Linear mixed-effect models](https://mspeekenbrink.github.io/sdam-r-companion/linear-mixed-effects-models.html#formulating-and-estimating-linear-mixed-effects-models-with-lme4)