project:
  type: website
editor:
  render-on-save: true
knitr: true
website:
  bread-crumbs: false
  favicon: /images/NEOF_favicon.png
  page-navigation: true
  title: Advanced R community analysis
  description: NEOF advanced R community analysis workshop site
  navbar:
    title: Adv. R comm
    logo: "images/NEOF_logo_no_background.png"
    collapse-below: lg
    left:
    - text: Overview
      href: index.qmd
    - text: Setup
      href: setup/setup.qmd
    - text: Rarefaction
      href: rarefaction/rarefaction.qmd
    - text: Divergence
      href: divergence/divergence.qmd
    - text: Upset
      href: upset/upset.qmd
    - text: MaAsLin3
      href: maaslin3/maaslin3.qmd
    - text: Metadata
      href: metadata/metadata_exploration.qmd
    - text: Appendix
      href: appendix/resources.qmd
    right:
    - icon: house-fill
      href: https://neof.org.uk/training/
      aria-label: Neof website
    - icon: linkedin
      href: https://www.linkedin.com/in/training-neof/
      aria-label: LinkedIn
    - icon: bluesky
      href: https://bsky.app/profile/nerc-eof.bsky.social
      aria-label: Bluesky
  page-footer:
    left: |
      [![](https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png){fig-alt="CC BY-SA 4.0" height=30px}](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    center: |
      [![](/images/NEOF_rounded_corners.png){fig-alt="NEOF" height=60px}](https://neof.org.uk/)
  sidebar:
  - id: Overview
    title: Overview
    style: floating
    align: left
    contents:
    - href: index.qmd
  - id: Setup
    title: Setup
    style: floating
    collapse-level: 2
    align: left
    contents:
    - href: setup/setup.qmd
  - id: Rarefaction
    title: Rarefaction
    style: floating
    collapse-level: 2
    align: left
    contents:
    - href: rarefaction/rarefaction.qmd
    - href: rarefaction/background.qmd
    - section: "Setup"
      contents:
      - href: rarefaction/data_and_setup.qmd
    - section: "Random seeds"
      contents:
      - href: rarefaction/random_seeds.qmd
      - href: rarefaction/r_and_random_seeds.qmd
      - href: rarefaction/random_seed_tasks.qmd
    - section: "Iterating rarefaction"
      contents:
      - href: rarefaction/iterating_rarefaction.qmd
      - href: rarefaction/phyla_relative_abundance.qmd
      - href: rarefaction/one_iteration.qmd
      - href: rarefaction/multiple_iterations.qmd
      - href: rarefaction/iteration_task.qmd
    - section: "Alpha diversity"
      contents:
      - href: rarefaction/alpha_intro.qmd
      - href: rarefaction/alpha_iterative_rarefaction.qmd
      - href: rarefaction/alpha_data_frame_tidy.qmd
      - href: rarefaction/alpha_violin_plot_and_stats.qmd
      - href: rarefaction/alpha_plot_with_stats.qmd
      - href: rarefaction/alpha_task.qmd
    - section: "Beta diversity"
      contents:
      - href: rarefaction/beta_intro.qmd
      - href: rarefaction/beta_distance_matrices.qmd
      - href: rarefaction/beta_rarefaction.qmd
      - href: rarefaction/beta_ordination.qmd
      - href: rarefaction/beta_stats.qmd
      - href: rarefaction/beta_subset_ordination.qmd
      - href: rarefaction/beta_considerations.qmd
      - href: rarefaction/beta_task.qmd
    - section: "Rarefaction slopes"
      contents:
      - href: rarefaction/rareslope_intro.qmd
      - href: rarefaction/rarefaction_curve.qmd
      - href: rarefaction/rarefaction_slope_tibble.qmd
      - href: rarefaction/rareslope_boxplots.qmd
    - section: "Templates"
      contents:
      - href: rarefaction/iterative_rarefaction_diversity_loop.qmd
  - id: Divergence
    title: Divergence
    style: floating
    collapse-level: 2
    align: left
    contents:
    - href: divergence/divergence.qmd
    - section: "Setup"
      contents: 
      - href: divergence/data_and_setup.qmd
    - section: "Data format"
      contents:
      - href: divergence/divergence_data_format.qmd
      - href: divergence/lower_triangle.qmd
      - href: divergence/metadata_addition.qmd
      - href: divergence/upper_triangle.qmd
      - href: divergence/bind_long_tibbles.qmd
    - section: "Intra-group divergence"
      contents:
      - href: divergence/intra_divergence.qmd
      - href: divergence/intra_site_divergence.qmd
      - href: divergence/intra_media_exercise.qmd
    - section: "Inter-group divergence"
      contents:
      - href: divergence/inter_divergence.qmd
      - href: divergence/inter_site_divergence.qmd
      - href: divergence/inter_media_exercise.qmd
    - section: "Advanced"
      contents:
      - href: divergence/combined_plot.qmd
      - href: divergence/divergences_split_by_a_group.qmd
  - id: Upset
    title: Upset
    style: floating
    collapse-level: 2
    align: left
    contents:
    - href: upset/upset.qmd
    - section: "Setup"
      contents: 
      - href: upset/data_and_setup.qmd
      - href: upset/simple_bar_chart.qmd
    - section: "Data format"
      contents:
      - href: upset/upset_data_format.qmd
      - href: upset/phyloseq_to_tibble.qmd
      - href: upset/upset_tibble_creation.qmd
    - section: "Upset plots"
      contents:
      - href: upset/upset_plot.qmd
      - href: upset/all_in_one_code.qmd
      - href: upset/challenge_1.qmd
    - section: "Lower taxa levels"
      contents:
      - href: upset/rare_removal_plot.qmd
      - href: upset/rare_upset_plot.qmd
    - section: "Metadata intersections"
      contents:
      - href: upset/metadata_sets.qmd
      - href: upset/sample_and_taxa.qmd
      - href: upset/metadata_and_taxa.qmd
      - href: upset/metadata_upset_plot.qmd
      - href: upset/media_genus_upset.qmd
      - href: upset/challenge_2.qmd
  - id: MaAsLin3
    title: Upset
    style: floating
    collapse-level: 3
    align: left
    contents:
    - href: maaslin3/maaslin3.qmd
    - section: "Background"
      contents:
      - href: maaslin3/linear_model.qmd
      - href: maaslin3/mixed_effects_model.qmd
      - href: maaslin3/logistic_model.qmd
    - section: "Setup"
      contents:
      - href: maaslin3/environment.qmd
    - section: "Data"
      contents: 
      - href: maaslin3/dataset.qmd
      - href: maaslin3/genus_aggregation.qmd
      - href: maaslin3/count_table.qmd
      - href: maaslin3/metadata.qmd
      - href: maaslin3\read_counts.qmd
    - section: "MaAsLin3 analysis"
      contents:
      - href: maaslin3/maaslin3_function.qmd
      - href: maaslin3/lme4.qmd
      - href: maaslin3/fixed_effects.qmd
      - href: maaslin3/random_effects.qmd
      - href: maaslin3/median_comparison.qmd
    - section: "Text output"
      contents:
      - href: maaslin3/html_table.qmd
      - href: maaslin3/metrics.qmd
      - href: maaslin3/text_task.qmd
    - section: "Output plots"
      contents:
      - href: maaslin3/plots.qmd
      - href: maaslin3/replot.qmd
      - section: Linear plots
        contents:
        - href: maaslin3/categorical_linear_plots.qmd
        - href: maaslin3/continuous_linear_plots.qmd
      - section: Logistic plots
        contents:
        - href: maaslin3/categorical_logistic_plots.qmd
        - href: maaslin3/continuous_logistic_plots.qmd
      - href: maaslin3/plot_types.qmd
      - section: Summary plot
        contents:
        - href: maaslin3/summary_plot.qmd
        - href: maaslin3/coefficient_plot.qmd
        - href: maaslin3/heatmap_plot.qmd
        - href: maaslin3/summary_plot_interpretation.qmd
  - id: Metadata
    title: Metadata
    style: floating
    collapse-level: 2
    align: left
    contents:
    - href: metadata/metadata_exploration.qmd
    - href: metadata/correlation.qmd
    - href: metadata/correlation_exploration.qmd
  - id: Appendix
    title: Appendix
    style: floating
    collapse-level: 2
    align: left
    contents:
    - href: appendix/resources.qmd
    - href: appendix/mamba.qmd
    - href: appendix/r_courses.qmd
    - href: appendix/faq.qmd
      
#Format
format:
  html:
    fig-width: 10.2
    fig-height: 6
###Include table of contents
### "On this page" right of page
    toc: true

###Page size
    grid:
####Width of sidebar
      sidebar-width: 200px
####Max width of main page
      body-width: 1200px
####Width of empty margin at right of toc
#### needed to give room for long headers
      margin-width: 150px
####Space separating body from sidebar and toc  
      gutter-width: 10px
###Code highlighting style
### a11y is accessible and auto switches between dark and light mode
    highlight-style: a11y

###Themes
###HTML themes: https://quarto.org/docs/output-formats/html-themes.html
    theme:
####Dark theme with scss file
      dark: [darkly, styles_dark.scss]
####Light theme with scss
      light: [styles_light.scss]
####Any text not determined in scss files will be mainfont
    mainfont: Lexend

####Code will overflow in code blocks
####set to scroll for scroll (i.e. horizontal scroll at bottom of block)
    code-overflow: wrap
###Paths for webexercises files
    css: include/webex.css
    include-after-body: include/webex.js